# Required: A short name for the action package
name: HiBob

# Required: A description of what's in the action package.
description: Creates a hibob account to a new employee

# Package version number, recommend using semver.org
version: 1.0.0

# The version of the `package.yaml` format.
spec-version: v2

dependencies:
  conda-forge:
    - python=3.11.11
    - python-dotenv=1.1.0
    - uv=0.6.11
  pypi:
    - sema4ai-actions=1.3.10

external-endpoints:
  - name: "Access HiBob API"
    description: "Accesses the API of HiBob"
    rules:
      - host: "api.hibob.com"
        port: 443


packaging:
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./venv/**
    - ./.venv/**
    - ./.DS_Store/**
    - ./**/*.pyc
    - ./**/*.zip
    - ./**/.env