# Required: A short name for the action package
name: Data Access Queries Template

# Required: A description of what's in the action package.
description: Actions for querying sales/customer data.

# Package version number, recommend using semver.org
version: 0.0.5

# The version of the `package.yaml` format.
spec-version: v2

dependencies:
  conda-forge:
    - python=3.11.11
    - uv=0.6.11
  pypi:
    - sema4ai-actions=1.3.11
    - sema4ai-data=1.0.3

packaging:
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./venv/**
    - ./.venv/**
    - ./.DS_Store/**
    - ./**/*.pyc
    - ./**/*.zip
    - ./**/.env

