# Required: A short name for the action package
name: License Guru

# Required: A description of what's in the action package.
description: Extract data for due diligence checks for dependencies

# Package version number, recommend using semver.org
version: 0.1.0

# The version of the `package.yaml` format.
spec-version: v2

dependencies:
  conda-forge:
  - python=3.11.11
  - uv=0.6.11
  pypi:
  - sema4ai-actions=1.3.10
  - requests=2.32.3
  - beautifulsoup4=4.12.3
  - anthropic=0.21.3

packaging:
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./venv/**
    - ./.venv/**
    - ./.DS_Store/**
    - ./**/*.pyc
    - ./**/*.zip
    - ./**/.env
